# Generated by Django 3.2.12 on 2022-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=25, verbose_name='ID_предложения')),
                ('hotel_id', models.IntegerField(verbose_name='ID_отеля')),
                ('price', models.IntegerField(verbose_name='стоимость')),
                ('currency', models.CharField(max_length=3, verbose_name='валюта')),
                ('acc_name', models.CharField(max_length=255, verbose_name='тип_проживания')),
                ('room_name', models.CharField(max_length=255, verbose_name='тип_комнаты')),
                ('meal_name', models.CharField(max_length=255, verbose_name='тип_питания')),
                ('meal_code', models.CharField(max_length=2, verbose_name='код_питания')),
                ('tariff_name', models.CharField(max_length=255, verbose_name='тип_тарифа')),
                ('date_begin', models.DateTimeField(verbose_name='дата_заезда')),
                ('date_end', models.DateTimeField(verbose_name='дата_выезда')),
                ('nights', models.IntegerField(verbose_name='число_ночей')),
                ('quote', models.IntegerField(verbose_name='квота')),
                ('comission', models.IntegerField(verbose_name='комиссия')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotelscomforts',
            name='comforts',
        ),
        migrations.RemoveField(
            model_name='hotelscomforts',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='hotelsrooms',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='hotelsrooms',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='roomscomforts',
            name='comforts',
        ),
        migrations.RemoveField(
            model_name='roomscomforts',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Comforts',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.DeleteModel(
            name='HotelsComforts',
        ),
        migrations.DeleteModel(
            name='HotelsRooms',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='RoomsComforts',
        ),
    ]
