# Generated by Django 3.2.12 on 2022-03-29 14:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20220329_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteloffers',
            name='cancellation_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='штраф_за_отмену_бронирования'),
        ),
    ]
