# Generated by Django 3.2.12 on 2022-03-29 15:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hoteloffers_cancellation_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteloffers',
            name='cancellation_info',
        ),
        migrations.AddField(
            model_name='hoteloffers',
            name='cancellation',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='штраф_за_отмену_бронирования'),
        ),
    ]
